DROP TABLE IF EXISTS LINEA_PEDIDO;
     
CREATE TABLE LINEA_PEDIDO (
  LINEA_PEDIDO_ID INT AUTO_INCREMENT PRIMARY KEY,
  PEDIDO_ID INT,
  PRODUCTO_ID INT NOT NULL,
  PRECIO DECIMAL(10,2) NOT NULL,
  CANTIDAD INT NOT NULL
);

DROP TABLE IF EXISTS PEDIDO;
     
CREATE TABLE PEDIDO (
  PEDIDO_ID INT AUTO_INCREMENT PRIMARY KEY,
  USUARIO_ID INT NOT NULL,
  ESTADO VARCHAR(100) DEFAULT 'PENDIENTE',
  IMPORTE_PAGO_GIFT DECIMAL(10,2) NOT NULL
);

