DROP TABLE IF EXISTS PRODUCTO;
     
CREATE TABLE PRODUCTO (
  PRODUCTO_ID INT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPCION VARCHAR(150) NOT NULL,
  SALDO_STOCK INT DEFAULT 0
);

INSERT INTO PRODUCTO (DESCRIPCION, SALDO_STOCK) VALUES
  ('CHORIZO AHUMADO', 25),
  ('JAMÓN SERRANO',31),
  ('MAYONESA HELLMANS', 18),
  ('COPOS AVENA', 42);