DROP TABLE IF EXISTS USUARIO;
	 
CREATE TABLE USUARIO (
  USUARIO_ID INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(50) NOT NULL,
  APELLIDOS VARCHAR(150) NOT NULL,
  SALDO_GIFT DECIMAL(10,2) DEFAULT 0.00
);

INSERT INTO USUARIO (NOMBRE, APELLIDOS, SALDO_GIFT) VALUES
  ('HANK','REARDEN', 390.0),
  ('JUAN','DE MARIANA', 250.0),
  ('FRANCISCO','DE VITORIA', 427.0),
  ('ELLIS', 'WYATT', 322.0),
  ('JAMES J.','HILL',421.0);
